server:
  port: 8080

spring:
  application:
    name: election
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: ${SISFIN_BACKEND_ENVIROMENT}

  datasource:
    url: jdbc:h2:mem:election
    username: election
    password: election
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect